import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconEye,
  IconEyeOff,
  IconShieldHalfFilled,
  IconMoneybag,
  IconUsers,
  IconCopy,
  IconPhotoEdit,
  IconKey,
  IconDeviceMobile,
  IconDeviceDesktop,
  IconFidgetSpinner,
  IconShield,
  IconUserBolt,
  IconBrandRedux,
  IconUserPlus,
  IconDots,
  IconUserMinus,
  IconRestore,
  IconChevronDownFilled,
  IconBrandStripe,
  IconClipboardX,
  IconLayoutCollage,
  IconSearch,
  IconRefresh,
  IconWorld,
  IconStar,
  IconMessageCircle,
  IconCamera,
  IconRobot,
  IconReportMoney,
  IconClick,
  IconImageGeneration,
  IconCrown
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  userPlus: IconUserPlus,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  eye: IconEye,
  eyeOff: IconEyeOff,
  security: IconShieldHalfFilled,
  moneyBag: IconMoneybag,
  users: IconUsers,
  copy: IconCopy,
  photoEdit: IconPhotoEdit,
  key: IconKey,
  mobile: IconDeviceMobile,
  desktop: IconDeviceDesktop,
  spinner2: IconFidgetSpinner,
  shield: IconShield,
  admin: IconUserBolt,
  redux: IconBrandRedux,
  dots: IconDots,
  userMinus: IconUserMinus,
  restore: IconRestore,
  arrowDown: IconChevronDownFilled,
  stripe: IconBrandStripe,
  clipboardX: IconClipboardX,
  fileText: IconFileText,
  layout: IconLayoutCollage,
  search: IconSearch,
  refresh: IconRefresh,
  globe: IconWorld,
  star: IconStar,
  messageCircle: IconMessageCircle,
  camera: IconCamera,
  robot: IconRobot,
  reportMoney: IconReportMoney,
  clickCourser: IconClick,
  imageGeneration: IconImageGeneration,
  crown: IconCrown
};
